title: Tom Kroll
email: tlkroll@yahoo.com
description: >- 
  Graduate Cybersecurity Student
baseurl: "" 
url: "" 
layouts_dir: "my_layouts"
github_username:  tlkroll

theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

markdown: kramdown